require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.1.4
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/*
    - node_modules/**/*
    - .simplecov
    - tmp/**/*
    - vendor/**/*

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 90
  AllowedPatterns:
    - '^\s*describe\s.+\sdo$'
    - '^\s*it\s.+\sdo$'
    - '^\s*context\s.+\sdo$'
    - 'expect'
    - '#'

Lint/AmbiguousBlockAssociation:
  AllowedMethods:
    - not_change

Lint/MissingSuper:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Exclude:
    - features/**/*

Style/BlockDelimiters:
  AllowedMethods: []

Naming/AsciiIdentifiers:
  Exclude:
    - features/**/*

Naming/PredicateName:
  AllowedMethods:
    - is_a?

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  AllowedMethods:
    - describe
    - context
    - it

Metrics/MethodLength:
  Max: 20
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Exclude:
    - app/models/concerns/nodes_search.rb
    - app/models/concerns/signable.rb
    - app/admin/concerns/document_shareable.rb

Rails/SkipsModelValidations:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

RSpec/NestedGroups:
  Max: 10

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

Lint/UselessTimes:
  Enabled: false

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false

Rails/TransactionExitStatement:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Naming/BlockForwarding:
  EnforcedStyle: explicit

Style/ArrayIntersect:
  Enabled: false
