version: '3.7'

services:
  postgres:
    container_name: postgres-local
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:13.5-alpine
    ports:
      - 5432:5432
    volumes:
          - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis-local
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres-data:
  redis-data: