version: '3.7'

services:
  postgres:
    container_name: postgres-local
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:13.5-alpine
    ports:
      - 5432:5432
    volumes:
          - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: