source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.4"

gem "rails", "~> 7.1.3.4"
gem "sprockets-rails"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "importmap-rails"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Websocket processing
gem 'faye-websocket', '~> 0.11.3'
gem 'eventmachine', '~> 1.2', '>= 1.2.0.1'

# ENV variables
gem 'dotenv-rails', '~> 2.1', '>= 2.1.1'

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "web-console"
end

